//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayitlar
    {
        public int Kayit_iD { get; set; }
        public int Kullanici_iD { get; set; }
        public int Kaynak_iD { get; set; }
        public Nullable<System.DateTime> Kayit_AlisTarih { get; set; }
        public Nullable<System.DateTime> Kayit_SonTarih { get; set; }
        public Nullable<bool> Kayit_Durum { get; set; }
    
        public virtual Kaynaklar Kaynaklar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
