//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int Kullanici_iD { get; set; }
        public string Kullanici_Ad { get; set; }
        public string Kullanici_Soyad { get; set; }
        public int Kullanici_Yas { get; set; }
        public string Kullanici_Cinsiyet { get; set; }
        public Nullable<int> Kullanici_KitapSayisi { get; set; }
        public Nullable<int> Kullanici_SayfaSayisi { get; set; }
        public Nullable<int> Kullanici_FavTuriD { get; set; }
        public string Kullanici_Tc { get; set; }
        public string Kullanici_Tel { get; set; }
        public Nullable<double> Kullanici_Ceza { get; set; }
        public int Kutuphane_iD { get; set; }
        public string Kullanici_Mail { get; set; }
    }
}
