//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutuphane
    {
        public int Kutuphane_iD { get; set; }
        public string Kutuphane_Ad { get; set; }
        public string Kutuphane_Sehir { get; set; }
        public int Kutuphane_KisiSayisi { get; set; }
    }
}
